### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-inheritence#1]
https://github.com/DenisPitsul/js-inheritence/blob/dcd4edb0f1b9e28655f518c52fb29b0856d3d204/assets/js/index.js#L13
- оскільки це ґеттер, то ним користуються синтаксисом властивостей, а властивості - це характерисики, вони зазвичай є іменниками, тобто краще буде отак:
```javascript
bmw.age
``` 
замість
```javascript
bmw.getAge
```

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/js-inheritence/commit/01490924b2e4ac092fc47dca170b0cb31fc6720f
